name: CI Build

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/backend.yml'
            frontend:
              - 'frontend/src/**'
              - 'frontend/*.json'
              - '.github/workflows/frontend.yml'
  backend:
    needs:
      - paths-filter
    if: needs.paths-filter.outputs.backend == 'true'
    uses: ./.github/workflows/backend.yml
    secrets: inherit
  
  frontend:
    needs:
      - paths-filter
    if: needs.paths-filter.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
  
  coveralls:
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
    if: always()
    steps:
      - name: Finish parallel build
        uses: coverallsapp/github-action@master
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          parallel-finished: true
          debug: 'true'
          carryforward: 'frontend,backend'